### ISSUE TITLE
Extension Installation from OS X Modeler 18 installs Malware

### ISSUE THREAD

**Issue by fausttiger007** [IBMPredictiveAnalytics/Word_Cloud_Visualization#1]
Installing the word_cloud_visualization extension from within OS X Modeler 18...  (El Capitan 10.11.4)
... first SPSS extension installation with a new install of R 3.2.2 ...    also installs Malware "OS X/Flashback.G"   in a file  "openssl.so"  which is in a  new   "openssl"  library installed during installation (or during first run).

"volume/Library/Frameworks/R.framework/Versions/3.2/Resources/library/openssl/libs/openssl.so.dSYM/Contents/Resources/openssl.so"

library "volume/Library/Frameworks/R.framework/Versions/3.2/Resources/library/openssl/"   did NOT exist before  extension installation and running.     I checked another OS X installation and it was not there, but appeared immediately after   installation.

OpenSSL was not installed previously, only the default installation of R 3.2.2 from RCran.

Fortunately  Anti-Virus (Intego) detects it instantly when one first runs the  Word Cloud in Modeler.
Quarantined file, and later deleted it.  It did not appear again when Word Cloud is run... but then no new installation is being downloaded (and using or installing OpenSSL)

Don't know if Malware is installed  because a corrupt   OpenSSL is installed to download the extension packages,   or if the R packages themselves  have the malware.

NOTE: Issue experienced on 2 separate OS X installations:
# 

unrelated Side comment:   R 3.2.2 is required for Modeler 18,  but when WordCLoud is run the Console Output reports:
    "Warning message: package 'NLP' was built under R version 3.2.3"

Tony

**Comment by tpinesBTA** [comment]
I guess one question is where the Openssl installation came from.    From R itself,  or from one of the packages downloaded/installed by the   R.script run by the extension.


R.script

# Install function for packages    
packages <- function(x){
  x <- as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}

packages(wordcloud)
packages(tm)
packages(rvest)
packages(RColorBrewer)

wrong.selection <- F

data.source <- %%textselection%%
field.list <- ''
if(data.source== 'web'){
u <- '%%url%%'
   if( u =='') wrong.selection <- T
selector <- '%%selector%%'
sample.text <- read_html(u)
ps<-html_nodes(sample.text, selector) %>%
  html_text()
} 


if(data.source =='local'){
path <- '%%path%%'
   if( path =='') wrong.selection <- T
  ps <- readLines(path)
} 

if(data.source =='modeler'){
   if('%%data%%' =='') wrong.selection <- T
          tmp <- strsplit('%%data%%',',')
          field.list <- gsub(" ", '', tmp[[1]])

if(length(field.list) == 1){
             ps <- modelerData[['%%data%%']]
    } else{
    ps <- lapply(field.list, function(x) {modelerData[[x]]})
}
}

if(nchar('%%savepath%%') > 0){
     save.path <-  '%%savepath%%'
     input.name <-  '%%filename%%'
     save <- T
}

name.count <<- 1

makeCloud <- function(x){
    ps <- paste(x, sep=" ", collapse="") 
    myCorpus = Corpus(VectorSource(ps))
    
    myCorpus = tm_map(myCorpus, tolower)
    if(%%rp%%) myCorpus =  tm_map(myCorpus, removePunctuation)
    if(%%rn%%)   myCorpus = tm_map(myCorpus, removeNumbers)
    if(%%rsw%%) myCorpus = tm_map(myCorpus, removeWords, stopwords("english"))
    corpus_clean <- tm_map(myCorpus, PlainTextDocument)
    myDTM = TermDocumentMatrix(corpus_clean, control = list(minWordLength = 1))
    m = as.matrix(myDTM)
    v  = sort(rowSums(m), decreasing = TRUE)
    set.seed(4363)
    palette <- brewer.pal(8,%%pal%%)

# save the image in png format

wordcloud(names(v), v, min.freq = %%min%%, max.words = %%max%%, random.order = F, random.color = T,rot.per=%%rotation%%, colors=palette)


# save the image in png format
if(save){
 name <- paste(save.path,'/' ,input.name,' ' , name.count, '.png',sep='')
png(name, width=%%wid%%, height= %%ht%%, units='in', res=300)
wordcloud(names(v), v, min.freq = %%min%%, max.words = %%max%%, random.order = F, random.color = T,rot.per=%%rotation%%, colors=palette)
dev.off()
name.count <<- name.count +1 
}


if(%%termfreqs%%)  print(v)  #prints term frequencies


}

graph.out <- ifelse((length(field.list) >1) || (%%byrow%%), lapply(ps,makeCloud),makeCloud(ps)) 
if(wrong.selection) print('You selected an invalid text source.  Update your selection of Modeler, Web, or Local data')

**Comment by fausttiger007** [comment]
I guess one question is where the Openssl installation came from. From R itself, or from one of the packages downloaded/installed by the R.script run by the extension.

R.script

 # Install function for packages  
packages <- function(x){
  x <- as.character(match.call()[[2]])
  if (!require(x,character.only=TRUE)){
    install.packages(pkgs=x,repos="http://cran.r-project.org")
    require(x,character.only=TRUE)
  }
}

packages(wordcloud)
packages(tm)
packages(rvest)
packages(RColorBrewer)

wrong.selection <- F

data.source <- %%textselection%%
field.list <- ''
if(data.source== 'web'){
u <- '%%url%%'
   if( u =='') wrong.selection <- T
selector <- '%%selector%%'
sample.text <- read_html(u)
ps<-html_nodes(sample.text, selector) %>%
  html_text()
} 

if(data.source =='local'){
path <- '%%path%%'
   if( path =='') wrong.selection <- T
  ps <- readLines(path)
} 

if(data.source =='modeler'){
   if('%%data%%' =='') wrong.selection <- T
          tmp <- strsplit('%%data%%',',')
          field.list <- gsub(" ", '', tmp[[1]])

if(length(field.list) == 1){
             ps <- modelerData[['%%data%%']]
    } else{
    ps <- lapply(field.list, function(x) {modelerData[[x]]})
}
}

if(nchar('%%savepath%%') > 0){
     save.path <-  '%%savepath%%'
     input.name <-  '%%filename%%'
     save <- T
}

name.count <<- 1

makeCloud <- function(x){
    ps <- paste(x, sep=" ", collapse="") 
    myCorpus = Corpus(VectorSource(ps))

```
myCorpus = tm_map(myCorpus, tolower)
if(%%rp%%) myCorpus =  tm_map(myCorpus, removePunctuation)
if(%%rn%%)   myCorpus = tm_map(myCorpus, removeNumbers)
if(%%rsw%%) myCorpus = tm_map(myCorpus, removeWords, stopwords("english"))
corpus_clean <- tm_map(myCorpus, PlainTextDocument)
myDTM = TermDocumentMatrix(corpus_clean, control = list(minWordLength = 1))
m = as.matrix(myDTM)
v  = sort(rowSums(m), decreasing = TRUE)
set.seed(4363)
palette <- brewer.pal(8,%%pal%%)
```

 # save the image in png format

wordcloud(names(v), v, min.freq = %%min%%, max.words = %%max%%, random.order = F, random.color = T,rot.per=%%rotation%%, colors=palette)

 # save the image in png format
if(save){
 name <- paste(save.path,'/' ,input.name,' ' , name.count, '.png',sep='')
png(name, width=%%wid%%, height= %%ht%%, units='in', res=300)
wordcloud(names(v), v, min.freq = %%min%%, max.words = %%max%%, random.order = F, random.color = T,rot.per=%%rotation%%, colors=palette)
dev.off()
name.count <<- name.count +1 
}

if(%%termfreqs%%)  print(v)  #prints term frequencies

}

graph.out <- ifelse((length(field.list) >1) || (%%byrow%%), lapply(ps,makeCloud),makeCloud(ps)) 
if(wrong.selection) print('You selected an invalid text source.  Update your selection of Modeler, Web, or Local data')

**Comment by fausttiger007** [comment]
Additional notes:
1) The process  'r_start'  connected to the internet during the extension installation

/Applications/IBM/SPSS/Modeler/18/SPSSModeler.app/Contents/ext/bin/pasw.rstats/r_start

2)  even though the openssl folder was added 5/13/16... the date on folder and the infected openssl.so resource inside is 5/6/16 1:58am.

"volume/Library/Frameworks/R.framework/Versions/3.2/Resources/library/openssl/libs/openssl.so.dSYM/Contents/Resources/openssl.so"

Tony

**Comment by fausttiger007** [comment]
False Positive..  so the  openssl is not infected.

Tony

> Thank you for your file submission.
> 
> Our malware team has reviewed the file you sent and they have identified it as a false positive. They expect that it will be corrected with an update that will be released Thursday. For now, please Trust the file by adding it to the Trusted Items. We apologize about the inconvenience.
> 
> Please let us know if you have any issues.
> 
> Kind Regards,
> 
> Babs
> Intego Support Team
